### DISCUSSION TITLE
Setting Per Object or Per Model Gravity

### DISCUSSION THREAD

**Discussion by adnanmunawar** [WPI-AIM/ambf#199] [Ideas]
The per object or per model gravity could be set like this:

```yaml
bodies: [BODY A, BODY B]
ignore inter-collision: false
gravity: {x: 0.0, y: 0.0, z: 1.0}  # Optional Model gravity, applied to all objects in the model
namespace: /ambf/env/
BODY A:
  name: A
  mesh: A.STL
  mass: 10.0
  gravity: {x: 0.0, y: -1.0, z: 0.0} # Optional Object gravity, overriding model or world gravity
  collision margin: 0.001
  scale: 1.0
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: -0.27, y: -0.01, z: 0.035}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.009, y: 0.0, z: 0.087}
  publish joint names: true
  publish joint positions: true
  friction: {rolling: 0.01, static: 0.5}
  damping: {angular: 0.1, linear: 0.04}
  restitution: 0
  collision groups: [0]
BODY B:
  name: B
  mesh: B.STL
  mass: 0.2  # No gravity specified so this Object will take the gravity defined at the model scope
  collision margin: 0.001
  scale: 1.0
  location:
    orientation: {p: -1.396, r: 1.396, y: -1.571}
    position: {x: -0.698, y: 0.291, z: 0.035}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: 0.0, z: -0.0}
  friction: {rolling: 0.01, static: 0.5}
  damping: {angular: 0.1, linear: 0.04}
  restitution: 0
  collision groups: [0]
```

In the above example, we have set the Model gravity and also an Object's gravity (for BODY A). The Model gravity will apply to Body B but Body A will override the gravity defined in its scope.
