### ISSUE TITLE
Specification of body and joint controllers using ADF files

### ISSUE THREAD

**Issue by adnanmunawar** [WPI-AIM/ambf#100]
In the current implementation, if controller gains are specified (for a body or a joint) in the ADF (the **.yaml** based AMBF Description File ) file, they are used to compute a **force** (wrench in case of cartesian control and torque/effort in case of joint control). This **output control type** (**force**) is then applied to the body/joint.

If the controller gains are not specified, a reasonable value of P and D gains is used but in this case, instead of computing an output force, an output velocity (twist in case of a body, velocity in case of a joint) is computed. This **output control type** (**velocity**) is then applied to the body/joint.

For body controllers, the **output control type** is further divided between **Cartesian position** and **Cartesian orientation**. Thus based on whether the linear and angular controllers are defined, a controller can have:

1. **output control type** of **force** for the position and an **output control type** of **velocity** for the orientation.
2. **output control type** of **velocity** for the position and an **output control type** of **force** for the orientation.
3. **output control type** of **force** for the position and the orientation.
4. **output control type** of **velocity** for the position and the orientation.

For IIDs (Input Interface Devices) which pair to an SDE (Simulated Dynamic End-Effector) which is a body in simulation, a controller can be specified in the `input_devices.yaml` file as seen here:

https://github.com/WPI-AIM/ambf/blob/ambf-1.0/ambf_models/descriptions/input_devices/input_devices_shadow.yaml#L83

```yaml
Razer Hydra0:
    hardware name: Razer Hydra
    haptic gain: {linear: 10.0, angular: 0.0}
    controller gain: {
      linear: {P: 0.0, D: 0.0},
      angular: {P: 50.0, D: 1.0}
      }
    # enable joint control: False # This flag disables the control of simulated dynamic bodies
    workspace scaling: 5
    # simulated multibody: "../multi-bodies/grippers/pr2 gripper.yaml"
    # root link: "/ambf/env/BODY l_wrist_roll_link"
    root link: /ambf/env/BODY r_gripper_palm_link
    location: {
      position: {x: 0.0, y: -1.0, z: 0},
      orientation: {r: 0.0, p: 0.0, y: 0.0}}
    # orientation offset: {r: 0.0, p: 0.0, y: 0}
    button mapping: {
      a1: 0,
      a2: 1,
      next mode: 2,
      prev mode: 3}
    # visible: True
    # visible size: 0.005
```

If a controller is specified here, it overrides the controller for that specific paired body.

To keep the implementation consistent, if a controller is specified in the `input_device.yaml` file, use its gains, and set the **output control type** as **force**. If no controller is specified, copy over the controller from the SDE which is being paired to the IID. Then set the **output control type** to whatever is specified by the controller of the SDE.
