### ISSUE TITLE
Errors when Publishing Images and Camera Feed

### ISSUE THREAD

**Issue by nnagururu** [WPI-AIM/ambf#127]
Just wanted to let you know that following the instructions in the wiki to publish images and camera feed I get a continuous "Error: invalid operation" in the terminal running the simulator. See below for error message

> ASYNCHRONOUS MULTI-BODY FRAMEWORK SIMULATOR (AMBF Simulator)
> 		(www.aimlab.wpi.edu)
> 		  (Copyright 2019)
> ____________________________________________________________
> 
> STARTUP COMMAND LINE OPTIONS: 
> 
> InputDevices Application Usage:
>   -h [ --help ]                     Show help
>   -n [ --ndevs ] arg                Number of Haptic Devices to Load
>   -i [ --load_devices ] arg         Index number of devices to load which is 
>                                     specified in input_device.yaml
>   -e [ --enableforces ] arg         Enable Force Feedback on Haptic Devices
>   -p [ --phx_frequency ] arg        Physics Update Frequency (default: 1000 Hz)
>   -d [ --htx_frequency ] arg        Haptics Update Frequency (default: 1000 Hz)
>   -t [ --fixed_phx_timestep ] arg   Use Fixed Time-Step for Physics (default: 
>                                     False)
>   -f [ --fixed_htx_timestep ] arg   Use Fixed Time-Step for Haptics (default: 
>                                     False)
>   -a [ --load_multibody_files ] arg Description Filenames of Multi-Body(ies) to
>                                     Launch, .e.g. -a <path>/test.yaml, 
>                                     <another_path>/test2.yaml will load 
>                                     multibodies test.yaml and test2.yaml if 
>                                     they are valid files
>   -l [ --load_multibodies ] arg     Index of Multi-Body(ies) to Launch, .e.g. 
>                                     -l 1,2,3 will load multibodies at indexes 
>                                     1,2,3. See launch.yaml file
>   --launch_file arg                 Launch file path to load (default: 
>                                     ../../ambf_models/descriptions/launch.yaml
>   -g [ --show_gui ] arg             Show GUI
>   --ns arg                          Override the default (or specified in ADF) 
>                                     world namespace
>   -s [ --sim_speed_factor ] arg     Override the speed of "NON REAL-TIME" 
>                                     simulation by a specified factor (Default 
>                                     1.0)
> 
> 
> ------------------------------------------------------------
> 
> 
> 
> INFO! WORLD CONFIG PATH: ../../ambf_models/descriptions/./world 
> Thread Joined: World
> INFO! SETTING SIMULATION MAX ITERATIONS TO : 50
> Thread Joined: light_left
> shader compilation failed:
> Parse error at prl_glsl_parse:252 ->>
> (14,2): error: initializer of type float cannot be assigned to variable of type uint
> (15,2): error: initializer of type float cannot be assigned to variable of type uint
> (16,2): error: initializer of type float cannot be assigned to variable of type uint
> (17,2): error: initializer of type float cannot be assigned to variable of type uint
> (19,20): error: LHS of operator << must be an integer or integer vector
> (19,20): error: type mismatch
> (19,31): error: LHS of operator << must be an integer or integer vector
> (19,31): error: type mismatch
> (19,20): error: LHS of `|' must be an integer
> (19,42): error: LHS of operator << must be an integer or integer vector
> (19,42): error: type mismatch
> (19,20): error: LHS of `|' must be an integer
> (19,20): error: LHS of `|' must be an integer
> (19,15): error: cannot construct `uint' from a non-numeric data type
> (20,15): error: LHS of operator << must be an integer or integer vector
> (20,15): error: type mismatch
> (20,26): error: LHS of operator << must be an integer or integer vector
> (20,26): error: type mismatch
> (20,15): error: LHS of `|' must be an integer
> (20,37): error: LHS of operator << must be an integer or integer vector
> (20,37): error: type mismatch
> (20,15): error: LHS of `|' must be an integer
> (20,15): error: LHS of `|' must be an integer
> (20,10): error: cannot construct `uint' from a non-numeric data type
> 
> shader compilation failed:
> Parse error at prl_glsl_parse:252 ->>
> (14,2): error: initializer of type float cannot be assigned to variable of type uint
> (15,2): error: initializer of type float cannot be assigned to variable of type uint
> (16,2): error: initializer of type float cannot be assigned to variable of type uint
> (17,2): error: initializer of type float cannot be assigned to variable of type uint
> (19,20): error: LHS of operator << must be an integer or integer vector
> (19,20): error: type mismatch
> (19,31): error: LHS of operator << must be an integer or integer vector
> (19,31): error: type mismatch
> (19,20): error: LHS of `|' must be an integer
> (19,42): error: LHS of operator << must be an integer or integer vector
> (19,42): error: type mismatch
> (19,20): error: LHS of `|' must be an integer
> (19,20): error: LHS of `|' must be an integer
> (19,15): error: cannot construct `uint' from a non-numeric data type
> (20,15): error: LHS of operator << must be an integer or integer vector
> (20,15): error: type mismatch
> (20,26): error: LHS of operator << must be an integer or integer vector
> (20,26): error: type mismatch
> (20,15): error: LHS of `|' must be an integer
> (20,37): error: LHS of operator << must be an integer or integer vector
> (20,37): error: type mismatch
> (20,15): error: LHS of `|' must be an integer
> (20,15): error: LHS of `|' must be an integer
> (20,10): error: cannot construct `uint' from a non-numeric data type
> Thread Joined: default_camera
> Thread Joined: Chassis
> Thread Joined: ShockBL
> Thread Joined: WheelBR
> Thread Joined: ShockBR
> Thread Joined: WheelBL
> Thread Joined: ShockFL
> Thread Joined: WheelFR
> Thread Joined: ShockFR
> Thread Joined: WheelFL
> Found Lib: libdvrk_arm.so
> No of dVRK Masters detected: 0
> WARNING: FAILED TO LOAD DEVICE: "MTMR"
> WARNING: FAILED TO LOAD DEVICE: "MTML"
> WARNING: FAILED TO LOAD DEVICE: "Geomagic Touch"
> WARNING: FAILED TO LOAD DEVICE: "Razer Hydra0"
> WARNING: FAILED TO LOAD DEVICE: "Razer Hydra1"
> WARNING: FAILED TO LOAD DEVICE: "Novint Falcon1"
> WARNING: FAILED TO LOAD DEVICE: "Novint Falcon2"
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
> Error:  invalid operation
>

The topics for ImageData and DepthData are still being published though, so not sure if it's really an issue. 

>  rostopic list
> /ambf/env/Chassis/Command
> /ambf/env/Chassis/State
> /ambf/env/ShockBL/Command
> /ambf/env/ShockBL/State
> /ambf/env/ShockBR/Command
> /ambf/env/ShockBR/State
> /ambf/env/ShockFL/Command
> /ambf/env/ShockFL/State
> /ambf/env/ShockFR/Command
> /ambf/env/ShockFR/State
> /ambf/env/WheelBL/Command
> /ambf/env/WheelBL/State
> /ambf/env/WheelBR/Command
> /ambf/env/WheelBR/State
> /ambf/env/WheelFL/Command
> /ambf/env/WheelFL/State
> /ambf/env/WheelFR/Command
> /ambf/env/WheelFR/State
> /ambf/env/World/Command
> /ambf/env/World/State
> /ambf/env/World/point_cloud
> /ambf/env/cameras/default_camera/Command
> /ambf/env/cameras/default_camera/DepthData
> /ambf/env/cameras/default_camera/ImageData
> /ambf/env/cameras/default_camera/ImageData/compressed
> /ambf/env/cameras/default_camera/ImageData/compressed/parameter_descriptions
> /ambf/env/cameras/default_camera/ImageData/compressed/parameter_updates
> /ambf/env/cameras/default_camera/ImageData/compressedDepth
> /ambf/env/cameras/default_camera/ImageData/compressedDepth/parameter_descriptions
> /ambf/env/cameras/default_camera/ImageData/compressedDepth/parameter_updates
> /ambf/env/cameras/default_camera/ImageData/theora
> /ambf/env/cameras/default_camera/ImageData/theora/parameter_descriptions
> /ambf/env/cameras/default_camera/ImageData/theora/parameter_updates
> /ambf/env/cameras/default_camera/State
> /ambf/env/lights/light_left/Command
> /ambf/env/lights/light_left/State
> /rosout
> /rosout_agg

**Comment by adnanmunawar** [comment]
Based on our earlier discussion, I shall explain the cause of the problem and a couple of solutions.

### Problem Cause:
The shaders being used to compute the depth are not versioned, thus depending upon the machine, we might run into issues.

### Proposed Solutions:
The solutions are implemented in the `restructure` branch. This is the world file from that branch

``` yaml
camera1:
  namespace: cameras/
  name: default_camera
  location: {x: 4.0, y: 0.0, z: 2.0}
  look at: {x: 0.0, y: 0.0, z: -0.5}
  up: {x: 0.0, y: 0.0, z: 1.0}
  clipping plane: {near: 0.1, far: 10.0}
  field view angle: 0.8
  monitor: 0
  # multipass: True
  # publish image: True
  # publish image interval: 1 # Publish every nth scene update
  publish depth: True
  # publish depth noise: {mean: 0.1, std_dev: 0.01, bias: 0.0}
  # publish depth interval: 1 # Publish every nth scene update
  # publish image resolution: {width: 640, height: 480}
  # depth shaders:
  #   path: ../../../ambf_shaders/depth
  #   vertex: "shader.vs"
  #   fragment: "shader.fs"
```
 
#### Solution 1:
 In the world.yaml file, enable the external shaders as follows:
``` yaml
camera1:
  namespace: cameras/
  name: default_camera
  location: {x: 4.0, y: 0.0, z: 2.0}
  look at: {x: 0.0, y: 0.0, z: -0.5}
  up: {x: 0.0, y: 0.0, z: 1.0}
  clipping plane: {near: 0.1, far: 10.0}
  field view angle: 0.8
  monitor: 0
  # multipass: True
  # publish image: True
  # publish image interval: 1 # Publish every nth scene update
  publish depth: True
  # publish depth noise: {mean: 0.1, std_dev: 0.01, bias: 0.0}
  # publish depth interval: 1 # Publish every nth scene update
  # publish image resolution: {width: 640, height: 480}
  depth shaders:
    path: ../../../ambf_shaders/depth
    vertex: "shader.vs"
    fragment: "shader.fs"
```
This solution will use the shader files as specified in the depth shaders field. These shader use GLSL version 330 so should be ideal for modern hardware.

#### Solution 2 
The GLSL version of 330 is not supported on all virtual machines so it might be easier to use a shader written an older GLSL version. Thus for this solution, just modify the file as follows;

``` yaml
camera1:
  namespace: cameras/
  name: default_camera
  location: {x: 4.0, y: 0.0, z: 2.0}
  look at: {x: 0.0, y: 0.0, z: -0.5}
  up: {x: 0.0, y: 0.0, z: 1.0}
  clipping plane: {near: 0.1, far: 10.0}
  field view angle: 0.8
  monitor: 0
  # multipass: True
  # publish image: True
  # publish image interval: 1 # Publish every nth scene update
  publish depth: True
  # publish depth noise: {mean: 0.1, std_dev: 0.01, bias: 0.0}
  # publish depth interval: 1 # Publish every nth scene update
  # publish image resolution: {width: 640, height: 480}
  depth shaders:
    path: ../../../ambf_shaders/depth
    vertex: "shader_old.vs"
    fragment: "shader_old.fs"
```
These `shader_old.fs` and `shader_old.vs` files are written for compatibility with GLSL version 130 which should have better support across virtual machines.
