### ISSUE TITLE
Issues with two cameras

### ISSUE THREAD

**Issue by nnagururu** [WPI-AIM/ambf#136]
Using two cameras one to publish image and depth and the other to publish segmentation maps.

Two low importance issues:
1. If only publishing image without depth, text appears at bottom of image which messes with segmentation
2. Currently, an ambf window populates for each camera, it would be nice if we were able to suppress the window for one of the cameras

**Comment by adnanmunawar** [comment]
To make a camera window invisible, set a flag called `visible: False` in the camera description in its ADF file. E.g. In the default [world.yaml](https://github.com/WPI-AIM/ambf/blob/ambf-2.0/ambf_models/descriptions/world/world.yaml), the main camera can be hidden by adding the flag mentioned above. Note however that if the `publish image` or `publish depth` flag is set to true, the image/depth shall still be streamed out.

``` yaml
camera1:
  namespace: cameras/
  name: default_camera
  location: {x: 4.0, y: 0.0, z: 2.0}
  look at: {x: 0.0, y: 0.0, z: -0.5}
  up: {x: 0.0, y: 0.0, z: 1.0}
  clipping plane: {near: 0.1, far: 10.0}
  field view angle: 0.8
  monitor: 0
  visible: False
  publish image: True
```
