### ISSUE TITLE
Specifying the monitor number in the camera description in the ADF file doesn't work

### ISSUE THREAD

**Issue by adnanmunawar** [WPI-AIM/ambf#188]
Setting the monitor number in the ADF file for the camera does not work as expected. The window is placed on the primary monitor, however, setting it to fulscreen puts it on the correct one, but undoing fulscreen puts it back on the primary monitor.

``` yaml
camera1:
  namespace: cameras/
  name: default_camera
  location: {x: 4.0, y: 0.0, z: 2.0}
  look at: {x: 0.0, y: 0.0, z: -0.5}
  up: {x: 0.0, y: 0.0, z: 1.0}
  clipping plane: {near: 0.1, far: 10.0}
  field view angle: 0.8
  monitor: 1 <---- This parameter
```
