### ISSUE TITLE
Fix camera parenting specified via the ADF file

### ISSUE THREAD

**Issue by adnanmunawar** [WPI-AIM/ambf#69]
Newer updates to the API have disabled camera parenting specified via the ADF file.

**Comment by adnanmunawar** [comment]
@nsujumnong Please check this commit as it fixes the camera parenting issue we discussed last week. To help you understand better, open this file:

https://github.com/WPI-AIM/ambf/blob/master/ambf_models/descriptions/world/world.yaml#L48
and look at the data-block 
```yaml
# This example is to show how to parent w.r.t another body.
# When a parent is defined, the location, look at and up
# vector are with respect to the parent and not the world origin
cameraEndoscope:
  namespace: cameras/
  name: endo_camera
  location: {x: 0.0, y: 0.0, z: -0.1}
  look at: {x: 0.0, y: 0.0, z: -0.5}
  up: {x: 1.0, y: 0.0, z: 0.0}
  clipping plane: {near: 0.01, far: 10.0}
  field view angle: 0.8
  monitor: 0
  # stereo: {mode: Passive, eye separation: 0.22, focal length: 2.0}
  parent: /ambf/env/ecm/BODY remote center link
  # multipass: True

```

If you launch the ECM (with CLI -l6) now, you should see this camera parented to the ECM remote center link. Just make sure to add this camera in line 3:

https://github.com/WPI-AIM/ambf/blob/master/ambf_models/descriptions/world/world.yaml#L3

such that it becomes
```yaml
cameras: [cameras, cameraEndoscope]
```
